### ISSUE TITLE
Sprint 1

### ISSUE THREAD

**Issue by Nokcreate** [ID-Start-Winter22/chat-team-1#19]
sprint 1: verschiedene storys durchgehen und mögliche antworten besprechen, konversationspfade einführen..
issues für sprint 1 planen

**Comment by EggiEl** [comment]
Tone of Voice und allgemeine Gesprächsabläufe passen soweit und entwickeln sich weiter. 

Verfeinerung und Einbindung der praktischen Funktionen sind in neuen Issue für Sprint 2 geöffnet
