### ISSUE TITLE
Important Functions 

### ISSUE THREAD

**Issue by Xixxxi** [ID-Start-Winter22/chat-team-1#2]
Als Student möchte ich wissen, wann ich welche Vorlesung habe.                   **(Intent: class_when)**
Als Student möchte ich wissen, wo welche Vorlesung stattfindet                     **(Intent: class_where)**
Als Student möchte ich wissen, wie die Kontaktdaten der Professoren sind     **(Intent: uni_contacts)**
Als Student möchte ich wissen, wann die Prüfungsanmeldung ist                    **(Intent: exam_when)**
 - Folgefragen beachten (bsp.: Wo melde ich mich an?  -> Antwort: Primuss)
 - 
Als Student möchte ich wissen, wo die Prüfungsanmeldung ist                        **(Intent: exam_where)**
Als Student möchte ich (meine Anfrage) zu Google weitergeleitet werden, sofern der Bot meine Frage nicht beantworten kann **(Intent: bot_google)**
- (Letmegooglethat.com -> Links speichern und als Antwort im Spezialfall präsentieren)

**Comment by EggiEl** [comment]
Hier noch einen link zu den Hauptfunktionen die wir implementiert haben. 

Gute Arbeit, wir haben so gut wie alles geschafft. Danke für die tolle Zusammenarbeit! 

https://github.com/ID-Start-Winter22/chat-team-1/wiki/Skills-des-Bots
