### ISSUE TITLE
StoryBoard nachbauen

### ISSUE THREAD

**Issue by Nokcreate** [ID-Start-Winter22/chat-team-1#20]
ein StoryBoard anhand des Feedbacks von Frau Weisser nachbauen.

**Comment by Xixxxi** [comment]
Mit Storyboard ist eine graphische Darstellung der Situation gemeint, in der ein Beispielnutzer unseren Chatbot nutzt.
(Gezeichnet, o.ä. ...)

**Comment by Xixxxi** [comment]
[Storyboard2.pdf](https://github.com/ID-Start-Winter22/chat-team-1/files/10201735/Storyboard2.pdf)
