### ISSUE TITLE
Issues in Wiki 

### ISSUE THREAD

**Issue by Nokcreate** [ID-Start-Winter22/chat-team-1#29]
Bearbeiten Sie jeweils Ihre Issues und dokumentieren Sie für jedes Issue in Ihrem Wiki auf der Sprint 1 Wiki Seite, wie Ihre Lösung aussieht. Schreiben Sie im Kommentar des Issues, wo die Dokumentation im Wiki zu finden ist.
Wenn Sie ein Issue vollständig bearbeitet haben, weisen Sie das Issue einem anderen Teammitglied als Reviewer zu. Vermerken Sie im Kommentar mögliche Fragen oder Anmerkungen für das Review. Wenn das Review erfolgreich ist, kommentiert der/die Reviewer das Issue und schließt das Issue.

**Comment by EggiEl** [comment]
Haben wir gut gemacht! https://github.com/ID-Start-Winter22/chat-team-1/wiki
