### ISSUE TITLE
Optional Functions

### ISSUE THREAD

**Issue by Xixxxi** [ID-Start-Winter22/chat-team-1#3]
Als Student möchte ich wissen, wie das Wetter in München ist                                             **(Intent: muc_wheater)**
Als Student möchte ich wissen, wie lange ich per Öffis zur Uni brauche                               **(Intent: uni_mvg)**

------------------
Als Student möchte ich wissen, wie ich mir im Ofen ein Tisch reservieren kann                    **(Intent: ofen_contact)**

Als Studentischer Mitarbeiter möchte ich, das meine Konversationen in einem Chat gespeichert werden **(Intent: chat_storage)**
Als Studentischer Mitarbeiter möchte ich, Links mit mehr Informationen zu bestimmten Anfragen   **(Intent: chat_storage)**

**Comment by EggiEl** [comment]
wir haben uns doch dazu entschlossen uns auf die hauptfunktionen zu konzentrieren. Die api von @michaeleggers und die mvg-action wurde aber beibehalten. 

die optionalen Termine sind nicht extern einzubinden, da sie nur statisch eingebunden hätten werden können. 

Prototyp kann jetzt die geplanten Hauptfunktionen. Gute Arbeit an alle !  


link zu den Funktionen: https://github.com/ID-Start-Winter22/chat-team-1/wiki/Skills-des-Bots
