### ISSUE TITLE
Branch/Tag für Sprint 1 anlegen 

### ISSUE THREAD

**Issue by Nokcreate** [ID-Start-Winter22/chat-team-1#30]
Erstellen Sie in Ihrem GitHub Repository einen 'Tag' mit dem Namen 'Sprint1' um den Stand von Code und Dokumentation nach Sprint 1 zu kennzeichnen. Es wird Ihr Stand des Repositorys mit dem Tag 'Sprint1' gewertet.
Stellen Sie sicher, dass sich alle Teammitglieder in die Teamarbeit einbringen.
Am Ende von Sprint 1 steht ein Sprint Review. Dieser wird am 16. Dezember während der Lehrveranstaltung durchgeführt. Beim Sprint Review führen Sie eine Demo des Chatbots vor.

**Comment by EggiEl** [comment]
# Erledigt

Habe einen neuen Branch angelegt und diesen getaggt. 

Sollte nochmal gemacht werden bevor wir Vorstellen: 

Die git Befehle dafür sind : 

> neuen Tag Erstellen: 
`git tag -a <tag name> -m "mesage"`
> schauen ob der Tag stimmt:
`git tag `
> den Tag auf den letzten commit pushen: 
`git push --tags`

**Comment by Nokcreate** [comment]
Merci Elias, der Link hierzu ist der folgende: https://github.com/ID-Start-Winter22/chat-team-1/releases/tag/Sprint_1
