### ISSUE TITLE
Übersicht Intents -> Intent-Tabelle

### ISSUE THREAD

**Issue by MartinLagleder** [ID-Start-Winter22/chat-team-1#32]
bitte eine übersicht der für Sprint 1 angelegten neuen Intents erstellen

**Comment by Nokcreate** [comment]
ham wa da.

**Comment by Nokcreate** [comment]
ist hier https://github.com/ID-Start-Winter22/chat-team-1/wiki/Skills-des-Bots#unsere-intents
