### ISSUE TITLE
Erweiterung des Intents "Wann_wo"

### ISSUE THREAD

**Issue by MartinLagleder** [ID-Start-Winter22/chat-team-1#35]
gezielteres Fragen wann du welches Fach wo hast möglich machen

**Comment by EggiEl** [comment]
funktioniert muss aber in Sprint 2 verbessert werden. Rasa erkennt manche sachen nicht ganz

**Comment by EggiEl** [comment]
Ich habe hierfür ein  neues Issue für Sprint 2 angelegt indem wir das verbessern sollten :) https://github.com/ID-Start-Winter22/chat-team-1/issues/39
