### ISSUE TITLE
Chatbot Icon in localhost ändern

### ISSUE THREAD

**Issue by Nokcreate** [ID-Start-Winter22/chat-team-1#36]
Gianni, kannst du unser Orgi Bild im local host 8000 durch die neue Archie.png austauschen?

**Comment by Xixxxi** [comment]
Ich pushs dann in Spint1_neu oder?

**Comment by Nokcreate** [comment]
yes

**Comment by Xixxxi** [comment]
<h1>Ist erledigt </h1>
