### ISSUE TITLE
notizen page

### ISSUE THREAD

**Issue by MartinLagleder** [ID-Start-Winter22/chat-team-1#38]
elias stell doch mal deine handschriftlichen notizen auf der "Notizen" Page online

**Comment by EggiEl** [comment]
Ich schicks hier mal rein. wär cool wenn das einer ins wiki tun könnte, der sich mit markdown auskennt bitte: 

[Rasa-ablauf konvo.pdf](https://github.com/ID-Start-Winter22/chat-team-1/files/10230370/Rasa-ablauf.konvo.pdf)
[Rasa-ablaufplan.pdf](https://github.com/ID-Start-Winter22/chat-team-1/files/10230371/Rasa-ablaufplan.pdf)
[Rasa_zusammenfassung_Eggenberger.pdf](https://github.com/ID-Start-Winter22/chat-team-1/files/10230372/Rasa_zusammenfassung_Eggenberger.pdf)

**Comment by Nokcreate** [comment]
Die Dateien sind hier hinterlegt https://github.com/ID-Start-Winter22/chat-team-1/wiki/Notizen
