### ISSUE TITLE
Weg von Statik hin zu API 

### ISSUE THREAD

**Issue by EggiEl** [ID-Start-Winter22/chat-team-1#40]
Die statischen Informationen durch eine Api oder Terminkalender ersetzen

**Comment by Nokcreate** [comment]
die aktuell beste alternative nach unserem zoom call ist die verwendung der api des google kalenders um dieses problem zu loesen

**Comment by EggiEl** [comment]
nine hat die möglichkeit eine Kalender Datei mit dem eingetragenen Stundenplan runterzuladen. Das sind die Daten, die direkt von den Professoren rausgegeben werden. Ich habe es geschafft sie in einem python programm auszulesen und in unseren chatbot zu implementieren. 

Statt API haben wir jetzt die Kalenderdatei. Daten sind jetzt extern

**Comment by EggiEl** [comment]
Wie beim letzten Gruppenmeeting besprochen und erledigt.

**Comment by EggiEl** [comment]
Hier der Link zum Github Wiki Eintrag. Dokumentation der Probleme im Informatik Teil und Lösungskonzepten bei der Einbindung externer Daten

**Comment by EggiEl** [comment]
Wurde von der Gruppe gereviewed bei einem Gruppentreffen
