### ISSUE TITLE
User Testing

### ISSUE THREAD

**Issue by Nokcreate** [ID-Start-Winter22/chat-team-1#42]
Usability concept testing von mind. drei personen unserer zielgruppe mit dokumentation der ergebnisse.
Grundlage hierfuer ist unsere Vorlage auf dem Miro Board: https://miro.com/app/board/uXjVP-pEp8g=/

**Comment by EggiEl** [comment]
Miroboard wurde ausgefüllt und von der Gruppe abgesegnet.

**Comment by EggiEl** [comment]
Der Link zu den Ergebnissen des User-testings  und Dokumentation des Testings hier auf dem Miro Board im Wiki: https://github.com/ID-Start-Winter22/chat-team-1/wiki/Sprint-2#design

Wurde von der Gruppe bei einem Gruppentreffen reviewed
