### ISSUE TITLE
Zusammenfassung der Designergebnisse als eine PDF siehe Aufgabenstellung Moodle

### ISSUE THREAD

**Issue by EggiEl** [ID-Start-Winter22/chat-team-1#47]
Wir haben es fast übersehen, sollen aber noch unsere Designergebnisse in einer PDF Zusammenfassen.

**Comment by Nokcreate** [comment]
ist fertig und hier verlinkt: https://github.com/ID-Start-Winter22/chat-team-1/wiki/Sprint-2#zusammenfassung-design
