### ISSUE TITLE
Ergebnisse des User Testings noch besser ins Wiki einpflegen 

### ISSUE THREAD

**Issue by EggiEl** [ID-Start-Winter22/chat-team-1#48]
In der Aufgabenstellung steht, dass wir das Usertesting noch in unser Wiki aufbereiten sollen. 
Wir haben einen Link zum Miro Board drinnen und das Gesamtergebnis. Reicht das ? 

Bitte @Nokcreate noch ausführen. Sag falls du Hilfe benötigst.

**Comment by Nokcreate** [comment]
ist erledigt. gerne unter folgendem Link noch mal prüfen @EggiEl :
https://github.com/ID-Start-Winter22/chat-team-1/wiki/Sprint-2#design
