### ISSUE TITLE
external platforms

### ISSUE THREAD

**Issue by Xixxxi** [ID-Start-Winter22/chat-team-1#5]
- www.Letmegooglethat.com einbinden (Entweder: 1. Link auf Anfrage generieren Oder: 2. Links speichern und bei Spezialfällen wiedergeben)
- Anbindung an Hochschulportale (wie HM Seite, Moodle, Primuss, Nine)

**Comment by EggiEl** [comment]
letmegoogle that option nicht mehr implementiert. Wurde nicht für Sprint 2 als notwendig empfunden. 

Externe Plattform ist nun eine Kalenderdatei von nine siehe wiki: https://github.com/ID-Start-Winter22/chat-team-1/wiki/Sprint-2#probleme-und-l%C3%B6sungsstrategien-in-sprint-2

ich war Reviewer
